// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xntuktcrplpqpitweibc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhudHVrdGNycGxwcXBpdHdlaWJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODI2NTQsImV4cCI6MjA3MDE1ODY1NH0.AJnfRuR1nXWAtiSqYZFUbaTwfBvV0GG31xHyCTnZ00w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});